/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../App/HSI_App/HSI.h"
#include <stdio.h>
#include <string.h>
#include <stdint.h>

 int main(void) {
    // Initialize HSI clock (16MHz)
    HSI_Init();

    // Configure PA8 to output HSI clock on MCO1
    MCO1_OutputHSI();

    // Main program loop
    while(1) {
        // Your application code here
    }

    return 0;
}
