/**
 * @file pwm_led_hardware.h
 * @brief Behaviour: external LED breathing continuously, PWM generated by a timer.
 */

#ifndef PWM_LED_HARDWARE_H
#define PWM_LED_HARDWARE_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include <stdbool.h>
#include <stdint.h>

/* Exported functions --------------------------------------------------------*/

/**
 * @brief  Set up the timer PWM channel
 * @retval true on success
 */
bool PwmLedHardware_Init(void);

/**
 * @brief  Hand the brightness for this instant to the timer
 * @param  nowMs Current tick in milliseconds
 */
void PwmLedHardware_Task(uint32_t nowMs);

#ifdef __cplusplus
}
#endif

#endif /* PWM_LED_HARDWARE_H */
