/**
 * @file pwm_led_hardware.c
 * @brief Behaviour: external LED breathing continuously, PWM generated by TIM2.
 * @details Same waveform and same period as pwm_led_software.c, but TIM2 emits
 *          the carrier on its own. The task only writes a compare value, so the
 *          breath stays smooth no matter what the loop is doing.
 *
 *          The LED is never switched on or off by this module - only its duty
 *          cycle moves. A rhythm that forces the LED dark between pulses would
 *          read as a blink and hide the dimming entirely.
 */

/* Includes ------------------------------------------------------------------*/
#include "pwm_led_hardware.h"

#include "board.h"
#include "led_software_pwm.h"
#include "led_pwm_timer.h"

/* Private constants ---------------------------------------------------------*/
#define PWM_FREQUENCY_HZ   1000u   /**< Carrier; far above the flicker threshold */
#define FADE_PERIOD_MS     4000u   /**< One full dark -> bright -> dark breath */

/* Private variables ---------------------------------------------------------*/
static LedPwmTimer_t s_pwm;

/* Exported functions --------------------------------------------------------*/

bool PwmLedHardware_Init(void)
{
    const LedPwmTimerConfig_t config = {
        .port = BOARD_LED_EXT_PORT,
        .pin = BOARD_LED_EXT_PIN,
        .alternate = BOARD_LED_EXT_AF,
        .timer = BOARD_LED_EXT_TIM,
        .channel = BOARD_LED_EXT_TIM_CH,
        .pwmFrequencyHz = PWM_FREQUENCY_HZ
    };

    return LedPwmTimer_Init(&s_pwm, &config);
}

void PwmLedHardware_Task(uint32_t nowMs)
{
    uint8_t brightness = LedPwm_Waveform_Smooth(nowMs, FADE_PERIOD_MS);

    /* The waveform wraps on its own period, so no start time has to be kept. */
    LedPwmTimer_SetBrightness(&s_pwm, brightness);
}
