/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

 #include <stdio.h>
 #include "../App/HSI_PLL/HSI_PLL.h"

 int main(void) {
     // Initialize HSI and PLL for 180MHz system clock
     HSI_PLL_Init();

     // Configure MCO1 to output PLL clock on PA8
     MCO1_OutputPLL();

     // Main program loop
     while(1) {
         // Your application code
     }

     return 0;
 }
