/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// Choose which clock to use by including the appropriate header
// #include "../App/HSI_App/HSI.h"
#include "../App/HSE_Clock/HSE.h"

int main(void) {
    // Initialize HSE clock (8MHz external crystal)
    HSE_Init();

    // Configure PA8 to output HSE clock on MCO1
    MCO1_OutputHSE();

    // Main program loop
    while(1) {
        // Your application code here
    }

    return 0;
}